### ISSUE TITLE
select k nearest neighbours

### ISSUE THREAD

**Issue by innocentbenninghofen** [djvanderlaan/reclin2#11]
Currently, the logic for selecting matching records is working in two ways:

- 1:1 matching using `select_greedy` or `select_n_to_m`
- Selection of pairs above a certain treshold using `select_treshold`

However, in the latter case, one needs to specify the treshold directly, even though the distribution of this value is not always known beforehand.

Alternatively, it should be possible to indicate the top k nearest neighbours or highest scoring candidate matches.

Similarly to `select_treshold`, a `select_top_k` command could look like this:

`pairs <- select_top_k(pairs, "top_weights", score = "weights",  k = 8)`

The above command can be implemented by hand utilising 2 rows of code with `data.table::frank` and `data.table::fifelse`, but I think it would be more convenient to implement it in the package directly.

**Comment by djvanderlaan** [comment]
What would the top 8 be? For each record from x the top 8 matching records from y?

**Comment by innocentbenninghofen** [comment]
> What would the top 8 be? For each record from x the top 8 matching records from y?

Exactly. In this example: The top 8 matching records from y with the highest score in `"weights"`.

Would be even better to include a character vector with column names to sort by multiple columns and mark the top k values.

In my implementation, i am using the following code to extract the top 50 matches:

```
pairs[, top_50 := frank(pairs, -var1, -var2, -var3, ties.method = "min")]

pairs[, top_50 := fifelse(top_50 <= 50, TRUE, FALSE)]
```

**Comment by djvanderlaan** [comment]
Wouldn't you need a `by = .x` in your example? Or do you really just want to top K pairs?

The algorithm `select_n_to_m` calls does have the option to set `n` and/or `m` to values different than 1 (hence the name and not `select_1to1` :smile: ) but this hasn't been exposed yet (I believe a value of `Inf` for `m` and 8 for `n` would be the same as your top 8). But this would still call `lpsolve` in the background and would, therefore, be quite slow and only work for small problems while this is not needed in this case. 

What is the reason for the extra variables? If this is not needed I could modify `select_greedy` to also accept a `n` and `m` (already have an implementation for that I needed for some project).

**Comment by innocentbenninghofen** [comment]
> Wouldn't you need a `by = .x` in your example? Or do you really just want to top K pairs?

In my example above I only included a single candidate in `x`, which is why i omitted the `by = .x`. I am really looking for the top k matches for every observation in `x`.

> The algorithm select_n_to_m calls does have the option to set n and/or m to values different than 1 (hence the name and not select_1to1 😄 ) but this hasn't been exposed yet (I believe a value of Inf for m and 8 for n would be the same as your top 8).

I might have misunderstood something and will have a look at the function again.

> What is the reason for the extra variables? If this is not needed I could modify `select_greedy` to also accept a `n` and `m` (already have an implementation for that I needed for some project).

This sounds like a possible solution. The additional variables are probably not needed, if the scoring is calculated beforehand.
