### ISSUE TITLE
Troublesome object masking when attaching the package

### ISSUE THREAD

**Issue by JsLth** [djvanderlaan/reclin2#12]
When attaching the package, the identical comparator function masks `base::identical`:

```
> library(reclin2)

Attaching package: ‘reclin2’

The following object is masked from ‘package:base’:

    identical
```

This leads to some functions using `getOption("viewer")` to just stop working:

```
> leaflet::leaflet()
Error in identical(height, "maximize") : 
  unused arguments (height, "maximize")

> shiny::paneViewer()("")
Error in identical(height, "maximize") : 
  unused arguments (height, "maximize")
```

```
> getOption("viewer")
function (url, height = NULL) 
{
    if (!is.character(url) || (length(url) != 1)) 
        stop("url must be a single element character vector.", 
            call. = FALSE)
    if (identical(height, "maximize")) 
        height <- -1
    if (!is.null(height) && (!is.numeric(height) || (length(height) != 
        1))) 
        stop("height must be a single element numeric vector or 'maximize'.", 
            call. = FALSE)
    invisible(.Call("rs_viewer", url, height, PACKAGE = "(embedding)"))
}
```

Currently, the only reliable workaround I'm aware of is to just load reclin2 instead of attaching it. Since `base::identical` is a pretty common function and this issue is quite hard to debug or even recognize, it might be a good idea to rename the comparator function.

**Comment by djvanderlaan** [comment]
Thanks for reporting. I did have doubt about naming the function `identical` :smile: However, in principle packages should use `<otherpackage>::<function>`  .... except for `base` :disappointed: . So you are right, it is probably better to rename the function. Do you have suggestions for an other name? Perhaps `equal` (not a base R function).

A temporary workaround would probably be to run 
```
identical <- base::identical
```
after loading `reclin2`

**Comment by JsLth** [comment]
It might be an alternative to add context to the comparator functions, such as `cmp_`. This is done by some packages, such as [COINr](https://bluefoxr.github.io/COINr/reference/index.html) (see the `a_` and `n_` functions) or some tidyverse-related packages like forcats (`fct_` and `lvls_`) to specify what these functions operate on. I think this would also clear up the fact that the comparator functions return functions to be used in other functions of this package and do not, in fact, compare x and y like one might expect when reading `identical` or `jarowinkler`.

**Comment by djvanderlaan** [comment]
Need to remove the old versions of these function in a next update of the package.
