### ISSUE TITLE
Consistency with inplace = TRUE for the predict- function

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [djvanderlaan/reclin2#17]
Hello!
in general the functions in your package do not return anything to the console when inplace = TRUE. This makes sense as "pairs" is modified in place. 
However, the predict function seems to be the only function which still prints out the result. I find this behaviour inconsistent and I think that you can easily fix it. 

```
library(reclin2)

data("linkexample1", "linkexample2")
pairs <- pair_blocking(linkexample1, linkexample2, "postcode")

compare_pairs(pairs, on = c("lastname", "firstname", "address", "sex"), inplace = TRUE) #use inplace, to avoid copying of object to save memory
print(pairs)

m <- problink_em(~ lastname + firstname + address + sex, data = pairs) #pairs should again be the first argument!

predict(m, pairs = pairs, add = TRUE, inplace = TRUE) #Should not print when using inplace = TRUE, if to be consistent with compare_pairs()
print(pairs)
```

Also note another comment I made: In problink_em I feel like for consistency, data should again be the first argument in this function.
If you want I can maybe also make a pr with the appropriate changes, I don't want to put it all on you. But you are probably faster as this is your package. Your call!

Have a nice day!

**Comment by djvanderlaan** [comment]
Thanks!

As for `problink_em`: I understand what you mean. The reason for choosing this order is that this conforms to the R-standard where modelling functions generally have the specification of the model as their first argument, e.g. `lm(y ~ x, data = dta)`.  The same with the predict functions that generally have an interface like: `predict(model, newdata = dta)`. I agree that especially when using pipe operators this can less practical.  But to keep consistency with the patterns used in R, I would like to keep it this way. 

As for the `inplace` argument: `predict` does not have an `inplace` argument so in your example it is ignored. However, the function actually might need such an argument. There is an `add` argument that adds the predictions to the pairs. At the moment this does seem to modify the original pairs so if functions like `inplace = TRUE` in that case. The other functions have a default value of `inplace = FALSE`. So what I would like to do is: Add an `inplace` argument with default value `FALSE` (that is only used when `add = TRUE`) ; when `inplace = TRUE` it will return the pairs invisibly.
