### ISSUE TITLE
After cluster_collect compare_vars seems to give incorrect results

### ISSUE THREAD

**Issue by djvanderlaan** [djvanderlaan/reclin2#2]
Check if this is the case. Possibly the mapping between x and .x in de data.table is incorrect.

**Comment by innocentbenninghofen** [comment]
I realized that the cluster_pair* functions call the normal pair* function once the x data.table has been split. This leads to .x identifiers being duplicated, as every node restarts the id value at 1. I suggest assigning the .x identifier prior to splitting the data.table to overcome this problem.

**Comment by innocentbenninghofen** [comment]
Removing

[`  group <- sample(group)`](https://github.com/djvanderlaan/reclin2/blob/231fb25e68904cd02855cfc517c5e9b5c3cba589/R/cluster_pair.R#L51)

from all cluster_pair* functions seems to solve the issue. I have tested this on the linkexample data.

**Comment by djvanderlaan** [comment]
Thanks for the comments. I will have another look at this next week.

**Comment by innocentbenninghofen** [comment]
Thank you for your efforts!

I have one more suggestion, concerning the vignettes:

The dark green and red code Elements on top of the brown background make it
unnecessarily hard to read, regardless of whatever monitor setup I am
working from.
You could fix the color scheme for better readability.

Ty and BR

**Comment by djvanderlaan** [comment]
I can replicate this with 

```
library(devtools)
library(parallel)
load_all()

cluster <- makeCluster(2)

data("linkexample1", "linkexample2")
pairs <- cluster_pair_blocking(cluster, linkexample1, linkexample2, "postcode")
pairs0 <- pair_blocking(linkexample1, linkexample2, "postcode")

cpairs <- cluster_collect(pairs)
cpairs <- cpairs[order(.x, .y)]

pairs0 <- pairs0[order(.x, .y)]

#attr(cpairs, "x") <- attr(cpairs, "x")[order(.id)]

cpairs <- compare_pairs(cpairs, c("lastname", "address"))
pairs0 <- compare_pairs(pairs0, c("lastname", "address"))

stopifnot(isTRUE(all.equal(cpairs$.x, pairs0$.x)))
stopifnot(isTRUE(all.equal(cpairs$.y, pairs0$.y)))
stopifnot(isTRUE(all.equal(cpairs$lastname, pairs0$lastname)))
stopifnot(isTRUE(all.equal(cpairs$address, pairs0$address)))
```

Problem seems to be that `attr(cpairs, "x")` is not in the right order. Uncommenting the line above fixes the issue; `cluster_collect` should reorder `x `.

**Comment by djvanderlaan** [comment]
@innocentbenninghofen The colours in the code blocks should be brighter now and better readable.
