### ISSUE TITLE
Alternative to filter_pairs_for_deduplication()

### ISSUE THREAD

**Issue by flavonoide** [djvanderlaan/reclin2#21]
Hi.

I'm a new R user. I have adapted an R script to remove duplicates from my database. This script was made using the reclin package.
When I tried to pass this script on to my colleagues, they were unable to install reclin, which is no longer available.
Now I'm trying to adapt this script to reclin2. But I couldn't find an equivalent function to filter_pairs_for_deduplication()

Is there an alternative to this function?

Thank you.

**Comment by djvanderlaan** [comment]
I will look into reclin. I was planning to remove reclin anyway somewhere in the near future, but weird that I did nog get notified. 

As for the filter function: this is no longer needed. The `pair_` functions have a `deduplication` argument that does the same. By doing it during the pair generation, the functions use less memory.

**Comment by djvanderlaan** [comment]
Closing this issue. I looked into reclin, but getting it to work again would have been too much work. Especially one of it's dependencies `ldat` gave a lot of issues.
