### ISSUE TITLE
problink_em fails with extremely high and low comparator scores

### ISSUE THREAD

**Issue by JsLth** [djvanderlaan/reclin2#23]
Sometimes when the comparison scores produced by `compare_pairs` reach extreme scores like complete (dis)similarity, 0 or 1, `problink_em` fails to estimate probabilities. Here is a reproducible example:

```r
library(reclin2)

ex1 <- data.frame(
  a = "aaaaa",
  b = "zzzzz"
)

ex2 <- data.frame(
  a = "bbbbb",
  b = "zzzzz"
)

pairs <- pair(ex1, ex2)
pairs <- compare_pairs(pairs, on = c("a", "b"), default_comparator = cmp_jarowinkler())

m <- problink_em(~ a + b, data = pairs)

# Error in if (mprobs[[col]] > mprob_max) mprobs[[col]] <- mprob_max : 
#  missing value where TRUE/FALSE needed
```

I am not entirely sure when exactly this happens, but it also seems to be linked to the fact that there are absolute 0's and absolute 1's present in the same row. I dug a bit into the source code of `problink_em` and figured out that the error occurs due to an NA value which is produced due to division by 0. In particular, the following line seems to produce this NA value (from [`problink_em.R#L77`](https://github.com/djvanderlaan/reclin2/blob/master/R/problink_em.R#L77C5-L77C32)

```r
gm <- p*a / (p*a + (1-p)*b)
```

This might seem like a fringe case (possibly reinforced by my absurd reprex), but in fact this came up in my day-to-day work with reclin2 on a regular basis. Sometimes, I'm able to work around this problem by just adding or subtracting a marginal number from the extreme scores, but this is not a reliable workaround, as the problem also seems to occur in case of scores very close to 0/1. See e.g. the following example in which a score of 0.999 leads to an error, but a score of 0.9 does not:

```r
pairs <- pair(ex1, ex2)
pairs <- compare_pairs(pairs, on = c("a", "b"), default_comparator = cmp_jarowinkler())

pairs$a <- pairs$a + 0.001
pairs$b <- pairs$b - 0.001
m <- problink_em(~ a + b, data = pairs)

# Error in if (mprobs[[col]] > mprob_max) mprobs[[col]] <- mprob_max : 
#   missing value where TRUE/FALSE needed


pairs <- pair(ex1, ex2)
pairs <- compare_pairs(pairs, on = c("a", "b"), default_comparator = cmp_jarowinkler())

pairs$a <- pairs$a + 0.1
pairs$b <- pairs$b - 0.1
m <- problink_em(~ a + b, data = pairs)

# M- and u-probabilities estimated by the EM-algorithm:
#  Variable M-probability U-probability
#         a             0         1e-04
#         b             0         1e-04
#
# Matching probability: 0.0001370404.
```

```r
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reclin2_0.3.4     data.table_1.14.8

loaded via a namespace (and not attached):
[1] compiler_4.3.1    parallel_4.3.1    tools_4.3.1       Rcpp_1.0.10       lpSolve_5.6.19    stringdist_0.9.10
```

**Comment by djvanderlaan** [comment]
Thanks for writing the clear reproducible examples!

In this case the m-probabilities converge to zero. The code now checks if this is the case and truncate the m-probabilities to a very small value (`uprob_min`) and give a warning. However, this very very likely does mean that the em-algorithm converged to a invalid solution as generally the m-probabilities should be close to 1. The m-probability is the probability that if we have the same object in both data sets, that the variable is equal. So a probility of 0 indicates that the variable will always be unequal when we have the same object. That would be weird. 

As for why 0.001 does not work and 0.1 does. `a` and `b` are the result of a jaro-winkler comparison. For the EM-algorithm there values betwen 0 and 1 need to be translated to FALSE/TRUE. By default values below 0.95 are translated to FALSE. In your example the values are either 0 or 1. So, by subtracting 0.1 you get 0.9 and this is smaller than 0.95, while subtracting 0.001 is still larger than 0.95.
