### ISSUE TITLE
Block pairs based on inequality condition?

### ISSUE THREAD

**Issue by etiennebacher** [djvanderlaan/reclin2#24]
Hello, thanks for the package and for the vignettes, they are extremely helpful.

One question I have is whether it is possible to do some kind of "inequality blocking" (I'm a beginner in the record linkage domain, maybe there's a specific term for this). In your first vignette, you block on the postal code, so it is quite easy to block pairs based on this condition. In my setting, I would like to add a limit on the year. 

Basically, I have a list of people who moved from country A to country B at different years (with names and year of arrival) and I have a list of letters (with the sender names and the year in which they were written). I'd like to match letter senders to passengers lists. In this case, I would like to ignore pairs of writers-passengers where the year of arrival > year of letter (the letter has to be written after the person arrived in the country). Therefore, I would like to do something like `pair_blocking(passengers, writers, "year_arrival < year_written")`, but that doesn't seem possible yet.

Is this kind of blocking in the scope of this package? Otherwise, are there other packages / techniques that you could recommend?

Thanks again

**Comment by djvanderlaan** [comment]
Hi @etiennebacher  

Sorry for the delay. This kind of blocking is possible using the `pair_minsim` method (I hope I understand the question correctly). With `pair_minsim` it is possible to pass custom comparison functions. In this case we can define a function that returns `TRUE` when the date of arrival is smaller than that of the letter:

```
library(reclin2)

letters <- data.frame(
  year = c(1900, 1910, 1920),
  name  = c("A", "A", "B")
  )

passengers <- data.frame(
  name = c("A", "B", "C"),
  year = c(1905, 1910, 1910)
  )

compare_year <- function(x, y) {
  if (!missing(y)) {
    x < y
  } else {
    x & !is.na(x)
  }
}

pair_minsim(passengers, letters, on = c("name", "year"),
  comparators = list(year = compare_year), minsim = 2)
```
This results in 
```
  First data set:  3 records
  Second data set: 3 records
  Total number of pairs: 2 pairs

   .x .y simsum
1:  1  2      2
2:  2  3      2
```
So for person "A" we only match the second letter and not the first which was sent before the arrival date. 

Note that this will run slower than `pair_blocking`.

**Comment by etiennebacher** [comment]
Oh I completely missed this `pair_minsim()` function, I should have read the manual more thoroughly. Thank you!
