### ISSUE TITLE
greedy() : max n/m not always respected

### ISSUE THREAD

**Issue by flownt** [djvanderlaan/reclin2#26]
The function reclin2::greedy, which greedily selects the 'best' matches within arity bounds does not always respect those bounds.

```
#BUG: Should select 4, not 5!
reclin2:::greedy(1:5, c(1,1,2,2,2), rep(1, 5), n=2, m=2)
```

This was found using
```
df_11 <- data.frame(x=c(1,2))
df_23 <- data.frame(x=c(1,1,2,2,2))
```
and a join on x (no blocking).

Note that swapping the arguments does give the right solution.
```
reclin2:::greedy(c(1,1,2,2,2), 1:5, rep(1, 5), n=2, m=2)
```

**Comment by djvanderlaan** [comment]
Thanks! There was indeed a bug in greedy in the following line: https://github.com/djvanderlaan/reclin2/blob/64edfbebdddbfdc19f805017a656e90974c7b5b8/src/greedy.cpp#L50

```
yseen[y[i]] = yseen[x[i]] + 1;
```

should be

```
yseen[y[i]] = yseen[y[i]] + 1;
```
This has now been fixed and regression tests added.
