### ISSUE TITLE
question on pair selection via greedy and m-to-n

### ISSUE THREAD

**Issue by mariusmborchert** [djvanderlaan/reclin2#27]
Dear Jan,

I am using the R reclin2 package you published to solve a record matching research question.
After applying a similarity calculation to assign a matching score to each combination of records I would like to use functions “greedy” and “m-to-n” to select the pairs that are considered to belong to the same record in the base record set.
Here, I can observe that some records are matched more than once, which obviously can lead to incorrect results. I am working with version 0.3.5 and understand that an issue has been fixed with the new version 0.5.0 for the select_greedy function, but not for the m-to-n function. Is it possible that the same kind of issue you fixed in greedy is also currently observable in m-to-n?

For reproduction I attach an excel file containing an example:
record 148 is paired with record 150 (row 110) and at the same time record 150 is paired with record 151 (row 132). 
Same for records 152/154 in row 152 and 154/156 (greedy, row 167) or 154/156 (m-to-n, row 168).
Label columns were generated using this code:

#### greedy approach
```
dt_pairs_application <- 
  reclin2::select_greedy(pairs = dt_pairs_application, 
                         variable = "LABEL_LM_AGG_SIM_GREEDY_APPROACH", 
                         score = "MATCH_PROB_LM_AGG_SIM",
                         threshold = 0.5 )
```

#### m to n approach
```
 dt_pairs_application <- 
   reclin2::select_n_to_m(pairs = dt_pairs_application, 
                          variable = "LABEL_LM_AGG_SIM_N_TO_M_APPROACH", 
                          score = "MATCH_PROB_LM_AGG_SIM",
                          threshold = 0.5 )
```
[dt_check.xlsx](https://github.com/djvanderlaan/reclin2/files/14813511/dt_check.xlsx)

**Comment by djvanderlaan** [comment]
Really, sorry for the very late response.  I can reproduce what you have observed. 

Are you doing deduplication? (The fact that .x is always smaller than .y suggests so).

If not, there is no problem. Records 150 from y is a difference record than 150 from x. So there should be no problem. 

If, you are doing deduplication. Then you are right, it should only link record 150 once. This is not something that was changed during recent updates. `select_greedy` and `select_n_to_m` always have assumed that x and y are different sets of records which is ok for record linkage, but not for deduplication. I will look into how to resolve this. Thanks for reporting.

**Comment by djvanderlaan** [comment]
I will close this one; created an issue for this #32
