### ISSUE TITLE
R 3.6.0 dependency?

### ISSUE THREAD

**Issue by tedmoorman** [djvanderlaan/reclin2#4]
Hi, is there any reason the package is dependent on R 3.6.0?

I tried to build the package for 3.5.3 and received the following message:
```
* checking for file ‘reclin2-master/DESCRIPTION’ ... OK
* preparing ‘reclin2’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
* saving partial Rd database
Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'simplermarkdown' not found
Execution halted
```
I was able to install the package without a build, but just curious in case I run into any trouble.

**Comment by djvanderlaan** [comment]
I don't think the package uses features specific to R3.6 or later. Development started with R 3.6 and later, so I haven't tested with older versions than that. You try running the tests in the package to b sure. 

The package does depend on `simplermarkdown` during building for building the vignettes. `simplermarkdown` was only recently released. I believe that when releasing a new package it is made available by CRAN for the then current version, the previous version and newer versions. So, I suppose `simplermarkdown` is not available for R3.5. It is only needed for the vignettes, so should not be needed for an install or building binary packages. Also, `simplermarkdown` should work on earlier versions.

**Comment by tedmoorman** [comment]
I ran the R code for all the vignettes, and everything looked good. When I ran `check()` in _devtools_ I received an error related to `simplermarkdown`.  It looks like that's the only compatibility issue, so I'll close this out. Thanks for the package!
