### ISSUE TITLE
How to keep diagonal in pair_minsim?

### ISSUE THREAD

**Issue by loukesio** [djvanderlaan/reclin2#5]
Dear djvanderlaan, 

First of all thank you for your wonderful package, for solving our hands and for introducing me to it!
My data looks like the example. I am clustering using stringdist and pair_minsin
``` r
library(tidyverse)
library(reclin2)
library(stringdist)

df <- tibble(fruits=c("anana","ananna","peach"))


my_dist <- function(x, y, ...){
  1 - stringdist(x, y, method=c("lv"))
}

p <- pair_minsim(df, on = "fruits", deduplication = TRUE,
                 default_comparator = my_dist, minsim = -2) 

p %>% 
  as.data.frame()
#>   .x .y simsum
#> 1  1  2      0
```
<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I have three fruits: anana, ananna, peach and I cluster to cluster based on similarity. anana & ananna are very close but peach are very far away. However I want to keep peach in the data even if it does not cluster with anyone but itself for further analysis.  But i just want to keep peach in the analysis, and not its relationships with the others and look  like

```
   .x .y simsum
    1  2      0
    3  3     1
```

Do you have an idea how I can do this through pair_minsim?
Honestly, thank you for your time

**Comment by djvanderlaan** [comment]
In general you don't want to compare records to itself. `deduplicate_equivalence` will return all records:

```
> deduplicate_equivalence(p, "group")
   fruits group
1:  anana     2
2: ananna     2
3:  peach     3
```

What you want is not that simple, if I understand you correctly you only want to add 'diagnonal' elements when there are not already in a pair. Fortunately, the pairs object is a regular `data.frame` so we can use the regular `data.frame` manipulations to get what we need. So something like

```

to_add <- data.frame(.x = seq_len(nrow(df)), .y = seq_len(nrow(df)), 
  simsum = 1)
to_add <- to_add[!(to_add$.x %in% p$.x), , drop = FALSE]
to_add <- to_add[!(to_add$.y %in% p$.y), , drop = FALSE]
p2 <- rbind(p, to_add)
# rbind drops attributes. Add attributes from the orignal pairs to the new pairs
attributes(p2) <- attributes(p)
```
Resulting in
```
> p2
  First data set:  3 records
  Second data set: 3 records
  Total number of pairs: 2 pairs

   .x .y simsum
1:  1  2      0
2:  3  3      1
```

**Comment by loukesio** [comment]
Dear @djvanderlaan,

My apologies for my late reply! 
your answer is very neat and helpful to me.

I highly appreciate
