### ISSUE TITLE
Blocking on multiple variables with OR condition

### ISSUE THREAD

**Issue by lucasmalherbe** [djvanderlaan/reclin2#8]
I'm trying to link dataframes dfA and dfB. I don't want to rely solely on one variable for blocking, so I'd like to use two blocking variables and consider the union of the two resulting sets of pairs as my potential pairs. Unfortunately, this case doesn't seem to be supported by the `pair_blocking` function.

I tried the following instruction to create a new `pairs` object:
`pairs <- unique(rbindlist(list(pair_blocking(dfA, dfB, "postcode"), pair_blocking(dfA, dfB, "birthyear"))))`

It seems like I'm losing information in the process, as I get the following error when calling `compare_pairs` on this object: 
`Error in UseMethod("compare_pairs", pairs): no applicable method for 'compare_pairs' applied to an object of class "c('data.table', 'data.frame')"`

**Comment by djvanderlaan** [comment]
You are right this is not supported yet although it is common to do so. This is probably something that should be added. 

It is possible to do this using the `pair_simsum` function. I am answering without access to a computer so the following will probably contain some errors:

```
compare_simsum(dfA, dfB, on = c("postcode", "birthyear"), minsim = 1)
```

This means that the pairs have to agree on at least one variable. This will be slower than blocking as here all pairs will be compared. 

As for the error. I will look into this. This should probably work. Possibly some attributes are dropped by `rbindlist` or `unique`. Possibly adding the 'pairs' class back to pairs might be enough to get it working again .

**Comment by lucasmalherbe** [comment]
That would be a useful feature.

`rbindlist` does drop some attributes from the `pairs` data.table: the 'pairs' class, the name of the blocking variable and the data from both dataframes. It works again after adding them back manually. The following code provides a `pairs` object which can then be used in the `compare_pairs` function:
```
pairs <- unique(rbindlist(list(pair_blocking(dfA, dfB, "postcode"), pair_blocking(dfA, dfB, "birthyear"))))
setattr(pairs, "class", c("pairs", class(pairs))) #add the 'pairs' class
setattr(pairs, "blocking_on", "postcode OR birthyear") #add info on blocking variables for the print function
setattr(pairs, "x", as.data.table(dfA)) #add first dataframe's data as x
setattr(pairs, "y", as.data.table(dfB)) #add second dataframe's data as y
```

I also tried the `compare_simsum` solution (which is indeed slower). The only difference I found concerns the handling of missing values. With the `compare_simsum` solution, a record containing a null value in one of the blocking variables will not be matched with any record from the other dataframe (even if there is a match on the other variable).

**Comment by djvanderlaan** [comment]
I just checked `pair_minsim`; you are right that records with missing values are dropped. This means that there is a bug in `pair_minsim`. I'll make a separate issue for that.

**Comment by djvanderlaan** [comment]
Added a `merge_pairs` function (and a `rbind`) to combine pairs, so now you should be able to do

```
pairs <- merge_pairs(
  pair_blocking(dfA, dfB, "postcode"),
  pair_blocking(dfA, dfB, "birthyear")
)
```

That should handle this case (and possibly some other cases too).
